<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>de.labathome</groupId>
		<artifactId>de-labathome-parent</artifactId>
		<version>1.0.2</version>
	</parent>

	<artifactId>java-trust-constr</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>java-trust-constr</name>
	<description>scipy.optimize.minimize(method='trust-constr') in Java</description>

	<url>${jonathanschilling.git.url}${project.name}</url>
	<scm>
		<connection>${jonathanschilling.git.root}${project.name}.git</connection>
		<developerConnection>${jonathanschilling.git.root}${project.name}.git</developerConnection>
		<url>${jonathanschilling.git.url}${project.name}/tree/master</url>
	</scm>
	<issueManagement>
		<url>${jonathanschilling.git.url}${project.name}/issues</url>
		<system>GitLab Issues</system>
	</issueManagement>

	<dependencies>
		<dependency>
			<groupId>dev.ludovic.netlib</groupId>
			<artifactId>blas</artifactId>
			<version>3.2.0</version>
		</dependency>
		<dependency>
			<groupId>dev.ludovic.netlib</groupId>
			<artifactId>lapack</artifactId>
			<version>3.2.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.11.0</version>
				<configuration>
					<release>17</release>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>3.2.5</version>
			</plugin>
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>buildnumber-maven-plugin</artifactId>
				<configuration>
					<doCheck>false</doCheck>
					<doUpdate>false</doUpdate>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>