#!/usr/bin/env python3
"""
One-shot generator for scipy reference values used in Java parity tests.

Run from the repository root:

    python3 src/test/python/regenerate_references.py

Each function below corresponds to a Java integration test under
`src/test/java/de/labathome/optimization/integration/`; the printed values are
copy-pasted into the test as the expected fixture. Re-run when scipy is
upgraded or a new test case is added — every reference value used by a Java
test should originate here so it can be reproduced.

Requires: scipy >= 1.10 (any version with `trust-constr` is fine).
"""

import numpy as np
from scipy.optimize import minimize, LinearConstraint, NonlinearConstraint


def _print_result(title, result):
    print(f"--- {title} ---")
    print(f"  x        = {np.array2string(np.asarray(result.x), precision=15, separator=', ')}")
    print(f"  fun      = {repr(float(result.fun))}")
    print(f"  nit      = {result.nit}")
    print(f"  status   = {result.status}")
    print(f"  message  = {result.message!r}")
    if hasattr(result, "optimality"):
        print(f"  opt      = {repr(float(result.optimality))}")
    if hasattr(result, "constr_violation"):
        print(f"  cv       = {repr(float(result.constr_violation))}")
    print()


def quadratic_on_hyperplane():
    """min x[0]^2 + x[1]^2  s.t.  x[0] + x[1] = 2.

    Closed form: optimum at (1, 1), f* = 2.
    """
    fun = lambda x: x[0] ** 2 + x[1] ** 2
    grad = lambda x: np.array([2 * x[0], 2 * x[1]])
    hess = lambda x: np.array([[2.0, 0.0], [0.0, 2.0]])
    A = np.array([[1.0, 1.0]])
    constraint = LinearConstraint(A, 2.0, 2.0)
    x0 = np.array([-1.0, 0.5])
    result = minimize(fun, x0, jac=grad, hess=hess, constraints=[constraint],
                      method="trust-constr", options={"xtol": 1e-10, "gtol": 1e-10})
    _print_result("quadratic_on_hyperplane", result)


def rosenbrock_on_hyperplane():
    """Rosenbrock with constraint x[0] + x[1] = 2.

    The unconstrained min (1, 1) lies on this hyperplane, so the constrained
    solution coincides with it.
    """
    fun = lambda x: (1 - x[0]) ** 2 + 100 * (x[1] - x[0] ** 2) ** 2

    def grad(x):
        a, b = x
        return np.array([
            -2 * (1 - a) - 400 * a * (b - a ** 2),
            200 * (b - a ** 2),
        ])

    def hess(x):
        a, b = x
        return np.array([
            [2 - 400 * b + 1200 * a ** 2, -400 * a],
            [-400 * a, 200],
        ])
    A = np.array([[1.0, 1.0]])
    constraint = LinearConstraint(A, 2.0, 2.0)
    x0 = np.array([0.5, 1.5])
    result = minimize(fun, x0, jac=grad, hess=hess, constraints=[constraint],
                      method="trust-constr", options={"xtol": 1e-10, "gtol": 1e-10})
    _print_result("rosenbrock_on_hyperplane", result)


def quadratic_inside_disk():
    """min (x-2)^2 + (y-2)^2  s.t.  x^2 + y^2 <= 1.

    Optimum on disk boundary closest to (2, 2): (1/sqrt(2), 1/sqrt(2)).
    """
    fun = lambda x: (x[0] - 2) ** 2 + (x[1] - 2) ** 2
    grad = lambda x: np.array([2 * (x[0] - 2), 2 * (x[1] - 2)])
    hess = lambda x: np.array([[2.0, 0.0], [0.0, 2.0]])
    constraint = NonlinearConstraint(
        lambda x: x[0] ** 2 + x[1] ** 2,
        -np.inf, 1.0,
        jac=lambda x: [[2 * x[0], 2 * x[1]]],
    )
    x0 = np.array([0.5, 0.5])
    result = minimize(fun, x0, jac=grad, hess=hess, constraints=[constraint],
                      method="trust-constr", options={"xtol": 1e-10, "gtol": 1e-10})
    _print_result("quadratic_inside_disk", result)


def main():
    print("# References for de/labathome/optimization/integration/*.java")
    print("# Generated by src/test/python/regenerate_references.py")
    print(f"# scipy = {__import__('scipy').__version__}")
    print()
    quadratic_on_hyperplane()
    rosenbrock_on_hyperplane()
    quadratic_inside_disk()


if __name__ == "__main__":
    main()
